
require('plugins.config.cmp')
require('plugins.config.comment')
require('plugins.config.explorer')
require('plugins.config.indent-guide')
require('plugins.config.lspsaga')
require('plugins.config.mason')
require('lsp.lspconfig')
require('plugins.config.project')
require('plugins.config.telescope')
--require('plugins.config.treesitter')
require('plugins.config.which-key')
